# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 41ed21df72418464335cb883af39d29efd2c445072afca34ab04c4ea9b33e70b101be7c95bcab1551d98b1ec1a414c0235d4d1528ea40f784b4848fa5a688158

test:
  secret_key_base: ee3b03753e01291d57e98aa3ef5000365723f5f1053001ad984260b46e4c3f5ad1cf876019d0248298bc8b5836775e934db37485291694c3c11d9e80a1915b29

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
